name: windows-release

on:
  workflow_dispatch:
  push:
    branches: [ main, release, migrate-release-workflows ]

jobs:
  build-sign-publish:
    name: Build, Sign, and Publish Windows artifacts
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.
        ref: migrate-release-workflows

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.201

    # Install Nerdbank.GitVersioning
    - uses: dotnet/nbgv@master
      with:
        setCommonVars: true
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration=WindowsRelease

    - name: Run Windows unit tests
      run: |
        dotnet test --configuration=WindowsRelease
    
    - name: Sign installer
      uses: ldennington/git-credential-manager/.github/workflows/run-esrp.yml@migrate-release-workflows
      with:
        path: .\out\windows\Installer.Windows\bin\Release\net472\gcmcore-win-x86-$env:GitBuildVersion.exe
        keycode: CP-230012
        operationcode: SigntoolSign